name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Alpine rootfs
        run: |
          mkdir -p alpine-rootfs
          curl -L https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/x86_64/alpine-minirootfs-3.22.1-x86_64.tar.gz | tar -xz -C alpine-rootfs

      - name: Setup musl cross-compiler
        run: |
          mkdir -p musl-cross-compiler &&
          curl -L https://github.com/bazel-contrib/musl-toolchain/releases/download/v0.1.27/musl-1.2.3-platform-x86_64-unknown-linux-gnu-target-x86_64-linux-musl.tar.gz |
          tar -xz -C musl-cross-compiler

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install musl target for Rust
        run: rustup target add x86_64-unknown-linux-musl

      # Copied from https://github.com/youki-dev/youki/blob/main/.github/workflows/basic.yml#L133
      - name: Disable AppArmor restrictions
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
